<?php
/**
 * Created by PhpStorm.
 * User: base
 * Date: 20.08.2019
 * Time: 20:48
 */

namespace app\models;


use yii\db\ActiveRecord;

class category extends ActiveRecord
{
    public static function tableName()
    {
        return parent::tableName(); // TODO: Change the autogenerated stub
    }

}